docs: 补充通过命令创建的说明
FEMessage/vue-sfc-cli pull request #97
Opened 2019-10-22 03:17 UTC by colmugx

## Why
fix #37 

- 实际上已经完成了该功能，但没有文档
- 使用参数名意义不明，需要修改

## How
- 接受组件名参数，从`npm`修改为`name`
- 补充文档

## Test
```
npx vue-sfc-cli --name log-viewer --owner FEMessage
```

## Docs
- `README.md`
- `README-zh.md`

2019-10-22 03:19 UTC, donaldshen approved these changes

2019-10-22 03:20 UTC, eviIIt approved these changes

2019-10-22 10:28 UTC, levy9527 requested changes

2019-10-22 10:28 UTC, levy9527 commented on README-zh.md
> +这对参数通常为同时使用。以命令形式生成组件，跳过询问过程。
以命令形式生成组件，跳过询问过程。它们通常成对出现。

2019-10-22 10:28 UTC, levy9527 commented on README.md
> +This pair of arguments is usually used together. generate component by command to skipped questioning.
these two arguments are usually used together to generate component without questioning.

2019-10-23 07:58 UTC, levy9527 approved these changes

2019-10-23 07:58 UTC, merged